# 工作流名称
name: Deploy Project

# 工作流触发设置
on:
  # push进入仓库时触发
  push:
    # 分支条件设置
    branches:
     - main

# 工作流作业
jobs:
  # 作业名称
  deploy-project:
    # 使用可复用工作流
    # 也可以通过GitHub仓库引用自己或其他人的工作流
    uses: ./.github/workflows/deploy.yml
    # 使用策略复用工作流，例如它会并发执行project-name为vblog-server-admin、
    # vblog-server-portal、vblog-server-search 的作业，
    strategy:
      # 矩阵，就是搭配出各种可能，依次复用，可以有多维矩阵
      matrix:
        # 矩阵的一行，行名称用于引用（可以有多行，多列）
        project-name: [ vblog-server-admin, vblog-server-portal, vblog-server-search ]
    # 发送过去的普通属性
    with:
      # 引用上面的矩阵
      project-name: ${{ matrix.project-name }}
    # 秘密，秘密可以在仓库中设置，可复用工作流要获取秘密属性，只能通过这里传播过去之后获取
    secrets:
      # server-host是自定义的秘密名，后面为引用仓库的秘密
      server-host: ${{ secrets.SERVER_HOST }}
      mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      elastic-password: ${{ secrets.ELASTIC_PASSWORD }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
